Server:
  RunMode: debug # release
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8080/static
  UploadImageMaxSize: 5000 # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
    - .bmp
Database:
  DBType: mysql
  UserName: root
  Password: 123456
  Host: 127.0.0.1:3306
  DBName: simple_ticktok
  TablePrefix: douyin_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Redis:
  Addr: 124.223.44.108:6379
  Password: zhouzhou233
  DB: 0
JWT:
  Key: douyin
  Secret: douyin
  Issuer: douyin-service
  Expire: 7200
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: XXXXX@qq.com
  Password: cxtksofwlawfdidg
  IsSSL: true
  From: XXXXX@qq.com
  To:
    - XXXXX@qq.com