Server:
  RunMode: debug # release
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadVideoMaxSize: 500 # MB
  UploadVideoAllowExts:
    - .mp4
Database:
  DBType: mysql
  UserName: douyin
  Password: Douyin@123
  Host: 106.14.89.192:3306
  DBName: douyin
  TablePrefix: douyin_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Redis:
  Addr: 106.14.89.192:6379
  Password: ""
  DB: 0
JWT:
  Key: douyin
  Secret: douyin
  Issuer: douyin-service
  Expire: 7200
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: 2664006323@qq.com
  Password: cxtksofwlawfdidg
  IsSSL: true
  From: 2664006323@qq.com
  To:
    - 717052740@qq.com